### ISSUE TITLE
97.00 is shown as 96.00

### ISSUE THREAD

**Issue by nanikit** [recursivebs/Visual-Score-Counter#12]
## Steps to reproduce

Get higher integer accuracy.
[video](https://streamable.com/li3wjb)

## Expected behavior
96.00 should be 97.00

## Actual behavior
why 96?

**Comment by recursivebs** [comment]
Have you updated the mod to the latest version? This was an issue in the past and has been fixed fairly recently

**Comment by nanikit** [comment]
I can't reproduce with the latest version. So close this.
